### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by zayn-0101** [malinkang/Podcast2Notion#2]
作者你好，我试过重新获取和填写变量，删除仓库重新fork重新配置，每次都仔细检查过，重试过不下十次，但依然failed，具体报错信息如下：
![image](https://github.com/malinkang/Podcast2Notion/assets/2428630/851f6c03-71ef-4a3d-a43b-5c8b8423c5c3)

**Comment by zion101** [comment]
![3272488dbc63eeb932a5ccfc2d731ac](https://github.com/malinkang/Podcast2Notion/assets/2428630/99b5b6f6-4954-4cd0-b5a4-9ec000a02ddd)

**Comment by malinkang** [comment]
同步代码就好了

**Comment by zayn-0101** [comment]
> 同步代码就好了

同步了的，还是失败
<img width="813" alt="截屏2024-05-01 01 04 29" src="https://github.com/malinkang/Podcast2Notion/assets/2428630/b95de1aa-de63-4940-b7f6-f393ab1f4021">

**Comment by malinkang** [comment]
再同步一下

**Comment by zayn-0101** [comment]
> 再同步一下

好嘞，这回是真的OK了
